name: pokedex
description: "Homework for CM."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: PokemonClassic
      fonts:
        - asset: fonts/Pokemon Classic.ttf
  uses-material-design: true
