name: hr_to_phone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  watch_connectivity: ^0.2.0
  wear_plus: ^1.2.1
  workout: ^0.6.5
  wakelock_plus: ^1.2.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
